name: CI

on:
  repository_dispatch:
    types: [export_scenario]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Display the path
      run: Get-ChildItem -Path .
      shell: pwsh
#    - name: Run Cmd
#      run: Get-ChildItem -Path . -Recurse -Force -Verbose
#      shell: powershell
    - name: Run a one-line script
      run: ls;Compress-Archive -Path .\* -DestinationPath archive.zip -Verbose;Install-Module -Name Xrm.Framework.CI.PowerShell.Cmdlets -RequiredVersion 9.0.0.8 -Force -Verbose;$connString = 'AuthType=Office365;Username=admin@crm681599.onmicrosoft.com;Password=MuWZ8q0yuN;Url=https://org4c1d55f2.crm.dynamics.com';$solPath = 'archive.zip';Import-XrmSolution -ConnectionString $connString -SolutionFilePath $solPath -Verbose
      shell: powershell
    - name: Webhook POST Action
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: https://prod-19.westcentralus.logic.azure.com:443/workflows/a0525663c2e14572b6d8ee5eea3af96d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=L2YXobc690TfB-ABmiqAucdLeC2WbSkBUjY8QcU6-Hg
        data: '{"data": "completed"}' 